version: '3.3'

services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
      - 80:80
    volumes:
      - wp_files:/var/www/html
    restart: unless-stopped
    networks:
      - wpnetwork

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    volumes:
     - wp_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wpnetwork
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - wp_files:/var/www/html
    networks:
      - wpnetwork
    restart: unless-stopped

networks:
  wpnetwork:
    driver: bridge

volumes:
    wp_files:
      driver: local
      driver_opts:
        type: none
        o: 'bind'
        device: './wordpress'
    dbdata:
      driver: local
      driver_opts:
        type: none
        o: 'bind'
        device: './data/db'