version: '3.3'

services:

  nginx:
    #build: ./requirements/nginx
    image: nginx:stable-alpine
    #container_name: nginx
    #depends_on:
    #  - wordpress
    #  - mariadb
    ports:
      - 80:80
     # - 443:443
    volumes:
      #- wpfiles:/var/www/html
      - ./wordpress:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    #networks:
     # - wpnetwork
    #restart: always

  wordpress:
    #build: ./requirements/wordpress
    image: php:7.4-fpm-alpine
    container_name: wordpress
    volumes:
     # - wpfiles:/var/www/html
     - ./wordpress:/var/www/html
    depends_on:
      - php
    #networks:
    #  - wpnetwork
    #restart: always

  php:
    #build: ./requirements/mariadb
    image: mysql:latest
    #container_name: mariadb
    environment:
      #MARIADB_DATABASE: wp
      #MARIADB_USER: wp
      #MARIADB_PASSWORD: secret
      #MARIADB_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

    volumes:
      #- ./requirements/mariadb:/var/lib/mysql
      #- wpfiles:/var/www/html
      - ./wordpress:/var/www/html
    #networks:
     # - wpnetwork
    #restart: always

#networks:
 # wpnetwork:

#volumes:
 # wpfiles: