version: '3.3'

services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    environment:
      - DOMAIN_NAME=apommier.42.fr
      - SSL_CERTIFICATE=/etc/ssl/certs/nginx-selfsigned.crt
      - SSL_CERTIFICATE_KEY=/etc/ssl/private/nginx-selfsigned.key 
    depends_on:
      - wordpress
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
    restart: unless-stopped
    networks:
      - wpnetwork

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
     - ./wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wpnetwork
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wpnetwork
    restart: unless-stopped

networks:
  wpnetwork:
    driver: bridge

volumes:
  wpfiles: