version: '3.3'

services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
    restart: unless-stopped
    networks:
      - wpnetwork

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
     - ./wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wpnetwork
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wpnetwork
    restart: unless-stopped

networks:
  wpnetwork:
    driver: bridge

volumes:
  wp_data: