version: '3.3'

services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    image: nginx:homemade
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp_files:/var/www/html
    restart: unless-stopped
    networks:
      - wpnetwork

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:homemade
    env_file: .env
    volumes:
     - wp_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wpnetwork
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:homemade
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - wpnetwork
    restart: unless-stopped

networks:
  wpnetwork:
    driver: bridge

volumes:
    wp_files:
      driver: local
      driver_opts:
        type: none
        o: 'bind'
        device: '/home/apommier/data/wordpress'
    dbdata:
      driver: local
      driver_opts:
        type: none
        o: 'bind'
        device: '/home/apommier/data/mariadb'