DROP DATABASE IF EXISTS test;
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'apommier'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'apommier'@'%';
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('1234');
FLUSH PRIVILEGES;