service mysql start 

printenv
echo Starting sql
echo $MARIADB_DATABASE -- data
echo $MARIADB_USER -- user
cat << EOF > mysql

CREATE DATABASE IF NOT EXISTS $MARIADB_DATABASE;
CREATE USER IF NOT EXISTS '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO '$MARIADB_USER'@'%';
FLUSH PRIVILEGES;
EOF

exit
